//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mise.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osobe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Osobe()
        {
            this.Detalji = new HashSet<Detalji>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Opaska { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Mobitel { get; set; }
        public string Email { get; set; }
        public string Slika { get; set; }
        public bool DaNe { get; set; }
        public Nullable<double> Iznos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalji> Detalji { get; set; }
    }
}
