//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mise.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervirane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervirane()
        {
            this.Detalji = new HashSet<Detalji>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int VrstaId { get; set; }
        public Nullable<bool> Obrisano { get; set; }
        public int NaruciteljID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalji> Detalji { get; set; }
        public virtual Vrsta Vrsta { get; set; }
    }
}
